### PR TITLE
Remove legacy globals from config

### PR DESCRIPTION
**Pull request by davidtaylorhq**
These should all now be imported from their associated es6 modules

Once published, this change should trigger dependabot to start making PRs across all plugins which use this module. Before merging those PRs, we'll have the opportunity to fix up any violations.

Note that these globals have been blocked via [core's .eslintrc](https://github.com/discourse/discourse/blob/5fd13380d8cf9b5c8d6f31be6dc18d9da4a77a10/.eslintrc) for some time

### CODE REVIEW

**Review by CvX — APPROVED** [review]
> Once published, this change should trigger dependabot to start making PRs across all plugins which use this module.

We don't have dependabot set up in plugins yet. It automatically creates PR only for security patches. We still have to create a dependabot config and distribute that to all repos.

**Comment by CvX** [comment]
Also, some plugins have `"eslint-config-discourse": "latest"` in their package.json, instead of e.g. `"eslint-config-discourse": "^1.1.9"` which also has to be changed

**Comment by davidtaylorhq** [comment]
> some plugins have "eslint-config-discourse": "latest" in their package.json

That should be ok, right? In fact, I would have thought `'latest'` was preferable?  Their `yarn.lock` files will still keep them on 1.1.9 until a `yarn upgrade`?

**Comment by CvX** [comment]
I think it's better to be specific about the current version in package.json. And I'm not sure how Dependabot handles deps that use "latest".

**Pull request merged**
